steps:
- name: 'ubuntu'
  args: ['echo', 'hello repos world']

serviceAccount: 'projects/test1-439421/serviceAccounts/292572785647-compute@developer.gserviceaccount.com'
options:
  logging: CLOUD_LOGGING_ONLY
